"""empty message

Revision ID: 64915052a575
Revises: 5ec19a8f1620
Create Date: 2021-04-25 01:29:47.473917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64915052a575'
down_revision = '5ec19a8f1620'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'favourites', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'favourites', 'cars', ['car_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favourites', type_='foreignkey')
    op.drop_constraint(None, 'favourites', type_='foreignkey')
    # ### end Alembic commands ###
